/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsInt,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { ReviewUpdateManyWithoutProfessionalsInput } from "./ReviewUpdateManyWithoutProfessionalsInput";
import { Type } from "class-transformer";
import { PortfolioWhereUniqueInput } from "../../portfolio/base/PortfolioWhereUniqueInput";
import { ServiceWhereUniqueInput } from "../../service/base/ServiceWhereUniqueInput";
import { ServiceUpdateManyWithoutProfessionalsInput } from "./ServiceUpdateManyWithoutProfessionalsInput";

@InputType()
class ProfessionalUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  experience?: number | null;

  @ApiProperty({
    required: false,
    type: () => ReviewUpdateManyWithoutProfessionalsInput,
  })
  @ValidateNested()
  @Type(() => ReviewUpdateManyWithoutProfessionalsInput)
  @IsOptional()
  @Field(() => ReviewUpdateManyWithoutProfessionalsInput, {
    nullable: true,
  })
  reviews?: ReviewUpdateManyWithoutProfessionalsInput;

  @ApiProperty({
    required: false,
    type: () => PortfolioWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PortfolioWhereUniqueInput)
  @IsOptional()
  @Field(() => PortfolioWhereUniqueInput, {
    nullable: true,
  })
  portfolio?: PortfolioWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ServiceWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ServiceWhereUniqueInput)
  @IsOptional()
  @Field(() => ServiceWhereUniqueInput, {
    nullable: true,
  })
  service?: ServiceWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ServiceUpdateManyWithoutProfessionalsInput,
  })
  @ValidateNested()
  @Type(() => ServiceUpdateManyWithoutProfessionalsInput)
  @IsOptional()
  @Field(() => ServiceUpdateManyWithoutProfessionalsInput, {
    nullable: true,
  })
  services?: ServiceUpdateManyWithoutProfessionalsInput;
}

export { ProfessionalUpdateInput as ProfessionalUpdateInput };
